import { Injectable } from '@angular/core';
import { Food } from 'src/app/shared/models/Food';
import {Tag} from '../../shared/models/Tag';
@Injectable({
  providedIn: 'root'
})
export class FoodService {
  constructor() { }

  getAllTags():Tag[]{
  return [
    {name:'All', count: 27},
    {name : 'Grain', count: 3},
    {name: 'Vegetable', count: 8},
    {name : 'Fruit', count: 4},
    {name : 'Oil', count: 2},
    {name : 'Seeds', count: 4},
    {name : 'Meat', count: 2},
    {name : 'Flour', count: 2},
    {name: 'Other', count: 2},
  ];
  }

  getAllFoodsByTag(tag: string): Food[] {
    return tag == "All" ? 
    this.getAll() : 
    this.getAll().filter(food => food.tags?.includes(tag));
  }

  getFoodById(id: number) : Food
  {
    return this.getAll().find(food => food.id == id)!;
  }


  getAllFoodsBySearchTerm(searchTerm: string) : Food[]{
    return this.getAll().filter(food =>
      food.name.toLowerCase().includes(searchTerm.toLowerCase()));
  }
  getAll(): Food[]{
  return [
    {
      id : 1, 
      name : "Wheet",
       deliveryTime : '3-5',
       price: 47,
       price_kg: "per kg",
        favorite: false,
        origins: ['High Nutrition'],
        stars: 4.8,
        imageUrl: '/assets/images/foods/wheet.jpg',
        tags: ['white', 'pulses', 'corn', 'All', 'Grain']
    },

    {
      id: 2,
      name: 'Rice',
      price: 32,
      price_kg: "per kg",
      deliveryTime: '3-5',
      favorite: true,
      origins: ['cerial', 'grain'],
      stars: 3.5,
      imageUrl: '/assets/images/foods/rice.jpg',
      tags: ['Grain', 'All'],
    },
    {
      id: 3,
      name: 'Onion',
      price: 30,
      price_kg: "per kg",
      deliveryTime: '2-3',
      favorite: false,
      origins: ['white onion','red onion','shallots','green onion'],
      stars: 4.0,
      imageUrl: '/assets/images/foods/onion.jpg',
      tags: ['RedOnion', 'Shallots', 'All', 'Vegetable'],
    },
    {
      id: 4,
      name: 'Potato',
      price: 60,
      price_kg: "per kg",
      deliveryTime: '2-3',
      favorite: true,
      origins: ['ground vegetable', 'starchy food'],
      stars: 3.3,
      imageUrl: '/assets/images/foods/potato.jpg',
      tags: ['GroundVegetable', 'All', 'Vegetable'],
    },
   
    {
      id: 5,
      name: 'Ladies Finger',
      price: 54,
      price_kg : "per half kg",
      deliveryTime: '1-2',
      favorite: false,
      origins: ['okra', 'hollyhock family'],
      stars: 3.0,
      imageUrl: '/assets/images/foods/ladiesfinger.jpg',
      tags: ['GreeenyVegetable', 'All', 'Vegetable'],
    },
    {
      id: 6,
      name: 'Drumstick',
      price: 15/1,
      price_kg: "",
      deliveryTime: '2',
      favorite: true,
      origins: ['Moringa', 'Moringaceae family'],
      stars: 2.8,
      imageUrl: '/assets/images/foods/drumstick.jpg',
      tags: ['drums', 'All', 'Vegetable'],
    },
    {
      id: 7,
      name: 'Tomato' ,
      price: 48,
      price_kg: "per kg",
      deliveryTime: '1-2',
      favorite: true,
      origins: ['Berry', 'Solanaceae family'],
      stars: 4.0,
      imageUrl: '/assets/images/foods/tomato.jpg',
      tags: ['orange', 'All', 'Vegetable'],
    },
    {
      id: 8,
      name: 'Brinjal' ,
      price: 51,
      price_kg: "per kg",
      deliveryTime: '1-2',
      favorite: false,
      origins: [ 'Eggplant', 'Solanaceae family'],
      stars: 3.8,
      imageUrl: '/assets/images/foods/brinjal.jpg',
      tags: ['Purple' , 'Vegetable','Eggplant', 'All'],
    },
    {
      id: 9,
      name: 'Carrot' ,
      price: 72,
      price_kg: "per kg",
      deliveryTime: '1-2',
      favorite: false,
      origins: ['orange', 'Daucus', 'Apiaceae family'],
      stars: 4.2,
      imageUrl: '/assets/images/foods/carrot.jpg',
      tags: ['orange', 'All', 'Vegetable'],
    },
    {
      id: 10,
      name: 'Beans' ,
      price: 31,
      price_kg: "per kg",
      deliveryTime: '1-2',
      favorite: false,
      origins: ['Fabaceae family', '5 Types'],
      stars: 3.8,
      imageUrl: '/assets/images/foods/beans.jpg',
      tags: ['green bean', 'All', 'Vegetable'],
    },

    {
      id: 11,
      name: 'Apple' ,
      price: 59,
      price_kg: "per kg",
      deliveryTime: '2-3',
      favorite: true,
      origins: ['Malus domestica'],
      stars: 5,
      imageUrl: '/assets/images/foods/apple.jpg',
      tags: ['Red', 'All', 'Fruit'],
    },
    {
      id: 12,
      name: 'Orange' ,
      price: 42,
      price_kg: "per kg",
      deliveryTime: '2-3',
      favorite: true,
      origins: ['hesperidium'],
      stars: 3.9,
      imageUrl: '/assets/images/foods/orange.jpg',
      tags: ['orange', 'All', 'Fruit'],
    },
    {
    id: 13,
    name: 'Banana' ,
    price: 30/10,
    price_kg: "",
    deliveryTime: '2',
    favorite: false,
    origins: ['Musaceae'],
    stars: 4.5,
    imageUrl: '/assets/images/foods/banana.jpg',
    tags: ['yellow', 'All', 'Fruit'],
  },
  {
    id: 14,
    name: 'Coconut',
    price: 15,
    price_kg: "",
    deliveryTime: '3-4',
    favorite: false,
    origins: ['Arecaceae'],
    stars: 2.5,
    imageUrl: '/assets/images/foods/coconut.jpg',
    tags: [ 'All', 'Fruit'],
  },
  {
    id: 15,
    name: 'chicken Meat' ,
    price: 121,
    price_kg: "",
    deliveryTime: '2',
    favorite: true,
    origins: ['Hen'],
    stars: 3.8,
    imageUrl: '/assets/images/foods/chicken.jpg',
    tags: ['Meat', 'All'],
  },
  {
    id: 16,
    name: 'Goat Meat' ,
    price: 242,
    price_kg: "",
    deliveryTime: '1-2',
    favorite: false,
    origins: [ 'goat'],
    stars: 3.8,
    imageUrl: '/assets/images/foods/goatmeat.jpg',
    tags: ['Meat', 'All'],
  },
  {
    id: 17,
    name: 'Bajra Flour' ,
    price: 82,
    price_kg: "",
    deliveryTime: '5',
    favorite: false,
    origins: ['bajra'],
    stars: 3.3,
    imageUrl: '/assets/images/foods/bajra_flour.jpg',
    tags: ['All', 'Flour'],
  },
  {
    id: 18,
    name: 'Wheet Flour' ,
    price: 121,
    price_kg: "",
    deliveryTime: '5',
    favorite: false,
    origins: ['wheet'],
    stars: 3.3,
    imageUrl: '/assets/images/foods/wheet_flour.jpg',
    tags: ['All', 'Flour'],
  },
  {
    id: 19,
    name: 'Chia Seeds' ,
    price: 12,
    price_kg: "",
    deliveryTime: '7',
    favorite: true,
    origins: ['Chia'],
    stars: 3.5,
    imageUrl: '/assets/images/foods/chia_seeds.jpg',
    tags: ['All', 'Seeds'],
  },
  {
    id: 20,
    name: 'Watermelon Seeds' ,
    price: 15,
    price_kg: "",
    deliveryTime: '7',
    favorite: true,
    origins: ['watermelon'],
    stars: 3.3,
    imageUrl: '/assets/images/foods/watermelon_seeds.jpg',
    tags: [ 'All', 'Seeds'],
  },
  {
  id: 21,
  name: 'Sunflower Seeds' ,
  price: 30,
  price_kg: "",
  deliveryTime: '7',
  favorite: false,
  origins: ['sunflower'],
  stars: 4.5,
  imageUrl: '/assets/images/foods/sunflowe_seeds.jpg',
  tags: ['flower', 'All', 'Seeds'],
},
{
  id: 22,
  name: 'Pumpkin Seeds' ,
  price: 30,
  price_kg: "",
  deliveryTime: '7',
  favorite: false,
  origins: ['pumpkin'],
  stars: 4.0,
  imageUrl: '/assets/images/foods/pumpkin_Seeds.jpg',
  tags: ['fruit', 'All', 'Seeds'],
},
{
  id: 23,
  name: 'Sunflower Oil' ,
  price: 61,
  price_kg: "",
  deliveryTime: '5',
  favorite: false,
  origins: ['sunflower'],
  stars: 2.0,
  imageUrl: '/assets/images/foods/sunflower_oil.jpg',
  tags: ['flower', 'All', 'Oil'],
},
{
  id: 24,
  name: 'Coconut Oil' ,
  price: 39,
  price_kg: "",
  deliveryTime: '7',
  favorite: false,
  origins: ['coconut'],
  stars: 3.3,
  imageUrl: '/assets/images/foods/coconut_oil.jpg',
  tags: ['fruit', 'All', 'Oil'],
},
{
  id: 25,
  name: 'Corn' ,
  price: 19,
  price_kg: "",
  deliveryTime: '7',
  favorite: false,
  origins: ['corn'],
  stars: 3.0,
  imageUrl: '/assets/images/foods/corn.jpg',
  tags: ['yellow', 'All', 'Grain'],
},
{
  id: 26,
  name: 'Pesticides' ,
  price: 121,
  price_kg: "",
  deliveryTime: '7',
  favorite: false,
  origins: ['sunflower'],
  stars: 3.3,
  imageUrl: '/assets/images/foods/pesticides.jpg',
  tags: ['All', 'Other'],
},
{
  id: 27,
  name: 'Cocopeat' ,
  price: 150,
  price_kg: "per kg",
  deliveryTime: '7',
  favorite: false,
  origins: ['Soil'],
  stars: 3.3,
  imageUrl: '/assets/images/foods/cocopeat.jpg',
  tags: ['All', 'Other', 'Bioproducts'],
},
  ];
  }
}
